---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-plugin-{{ .PluginName }}
  namespace: {{ .PluginNamespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .PluginName }}
      component: {{ .PluginName }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .PluginPort }}
  policyTypes:
    - Ingress
