apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
  name: {{ .PluginName }}
  namespace: {{ .PluginNamespace }}
  labels:
    app: {{ .PluginName }}
    app.kubernetes.io/component: {{ .PluginName }}
    app.kubernetes.io/instance: {{ .PluginName }}
    app.kubernetes.io/part-of: {{ .PluginName }}
spec:
  ports:
    - name: 9443-tcp
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: {{ .PluginName }}
  type: ClusterIP
  sessionAffinity: None
