apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-labelled-operator-olm
spec:
  podSelector:
    matchLabels:
      app: kubernetes-nmstate-operator
  policyTypes:
    - Ingress
    - Egress
